const cartTypes = {
	ADD_TO_CART: "ADD_TO_CART",
	SET_CART_ITEM: "SET_CART_ITEM",
	REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
	REDUCE_CART_ITEM: "REDUCE_CART_ITEM",
	CLEAR_CART: "CLEAR_CART",
	//new implementations
	ADD_BOOSTER_TO_CART: "ADD_BOOSTER_TO_CART"
};

export default cartTypes;
