export const rewards = {
  PRODUCT_DESCRIPTION: 2,
  PRODUCT_ADDITIONAL_DATA: 1,
  PRODUCT_PICTURE: 2,
  PRODUCT_MOVEMENT: 0.5,
  PRODUCT_CALIBER:0.5,
  PRODUCT_YEARS:0.5,
  PRODUCT_CASE_SIZE:1,
  PRODUCT_CASE_MATERIAL:1,
  PRODUCT_WATER_RESISTANCE:1,
};
