const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCT: "SET_PRODUCT",
  UPDATE_PRODUCT_VOTE_START: "UPDATE_PRODUCT_VOTE_START",
  FETCH_LATEST_PRODUCTS_START: "FETCH_LATEST_PRODUCTS_START",
  SET_LATEST_PRODUCTS: "SET_LATEST_PRODUCTS",
  FETCH_VALIDATION_PRODUCTS_START: "FETCH_VALIDATION_PRODUCTS_START",
  SET_VALIDATION_PRODUCTS: "SET_VALIDATION_PRODUCTS",
  UPDATE_PRODUCT_DETAILS_START: "UPDATE_PRODUCT_DETAILS_START",
  FETCH_RANDOM_PRODUCT: "FETCH_RANDOM_PRODUCT",
  SET_RANDOM_PRODUCT: "SET_RANDOM_PRODUCT",
  //
  FETCH_MY_COLLECTION_START: "FETCH_MY_COLLECTION_START",
  SET_MY_COLLECTION: "SET_MY_COLLECTION",
  FETCH_ALL_PRODUCTS_START: "FETCH_ALL_PRODUCTS_START",
  FETCH_COUNTERS_START: "FETCH_COUNTERS_START",
  SET_COUNTERS: "SET_COUNTERS",
};

export default productsTypes;
